<?php

namespace AppBundle\Repository;

/**
 * CommentRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
