<?php

namespace AppBundle\Repository;

/**
 * CommentRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRecipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsOfRecipe($idRecipe)
    {
        $qb = $this->createQueryBuilder('co')
            ->innerJoin('co.cookingRecipe', 'cr')
            ->addSelect('cr');

        $qb ->where('cr.id = :idRecipe')
            ->setParameter('idRecipe', $idRecipe);

        return $qb->getQuery()->getResult();
    }
}
