<?php

namespace AppBundle\Repository;

/**
 * CookingRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CookingRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
