<?php

namespace AppBundle\Repository;

/**
 * Ingredient_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllIngredientCategory()
    {
        $qb = $this->createQueryBuilder('ic')
            ->innerJoin('ic.image','im')
            ->addSelect('im');

         return $qb->getQuery()->getResult();

    }
}
