<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;
/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIngredientsOfCategory($idCategory)
    {
        $qb = $this->createQueryBuilder('i')
            ->innerJoin('i.category','c')
            ->addSelect('c');

        $qb->where('c.id = :idCategory')
            ->setParameter('idCategory',$idCategory);


        return $qb->getQuery()->getResult();
    }
}
