<?php

namespace AppBundle\Repository;

/**
 * PartOfMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartOfMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
