<?php

namespace AppBundle\Repository;

/**
 * SpecialtyCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialtyCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
