front_index:
    path:       /
    defaults:   { _controller: AppBundle:FrontOffice:index }

front-ingredient:
    path:       /categorie-ingredient/{id}
    defaults:   { _controller: AppBundle:FrontOffice:categoryIngredient }
    requirements:
        id:     \d+