app_bundle_front_office:
    resource: "@AppBundle/config/routing/front_office.yml"

app_bundle_back_office:
    resource: "@AppBundle/config/routing/back_office.yml"

app_bundle_manage_specialty_country:
    resource: "@AppBundle/config/routing/manage_specialty_country.yml"

app_bundle_manage_part_of_menu:
    resource: "@AppBundle/config/routing/manage_part_of_menu.yml"

app_bundle_manage_ingredient_category:
    resource: "@AppBundle/config/routing/manage_ingredient_category.yml"

app_bundle_manage_ingredient:
    resource: "@AppBundle/config/routing/manage_ingredient.yml"

app_bundle_manage_cooking_recipe:
    resource: "@AppBundle/config/routing/manage_cooking_recipe.yml"

app_bundle_manage_account:
    resource: "@AppBundle/config/routing/manage_account.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
