app_bundle_front:
    resource: "@AppBundle/config/routing/front.yml"

app_bundle_back:
    resource: "@AppBundle/config/routing/back.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
