app_bundle_front_office:
    resource: "@AppBundle/config/routing/front_office.yml"

app_bundle_back_office:
    resource: "@AppBundle/config/routing/back_office.yml"

app_bundle_manage_category:
    resource: "@AppBundle/config/routing/manage_category.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
