front_office_index:
    path:       /
    defaults:   { _controller: AppBundle:FrontOffice:index }

front_office_ingredient_category:
    path:       /categorie-ingredient/{id}
    defaults:   { _controller: AppBundle:FrontOffice:categoryIngredient }
    requirements:
        id:     \d+

front_office_ingredient:
    path:       /ingredient/{id}
    defaults:   { _controller: AppBundle:FrontOffice:ingredient}
    requirements:
        id:     \d+

front_office_part_menu:
    path:       /part-menu/{id}
    defaults:   { _controller: AppBundle:FrontOffice:partMenu }
    requirements:
        id:     \d+

front_office_country_specialty:
    path:       /recette-pays/{id}-{slug}
    defaults:   { _controller: AppBundle:FrontOffice:countrySpecialty }
    requirements:
        id:     \d+

front_office_add_recipe:
    path:       /ajouter-recette/
    defaults:   { _controller: AppBundle:FrontOffice:addRecipe }

front_office_recipe:
    path:       /recette/{id}-{slug}
    defaults:   { _controller: AppBundle:FrontOffice:recipe }
    requirements:
        id:     \d+

front_office_newsletter_inscription:
    path:      /newsletter-inscription/
    defaults:  { _controller: AppBundle:FrontOffice:newsletterInscription }

front_office_contact:
    path:     /contact
    defaults:  { _controller: AppBundle:FrontOffice:contact }

front_office_recipe_json:
    path:     /recipe-json
    defaults:  { _controller: AppBundle:FrontOffice:recipeJson }

front_office_search_recipe:
    path:     /search
    defaults:  { _controller: AppBundle:FrontOffice:searchRecipe }