front_office_vertical_menu_ingredients:
    path:       /all/ingredients
    defaults:   { _controller: AppBundle:FrontOfficeVerticalMenu:ingredients }

front_office_vertical_menu_parts_menu:
    path:       /all/partsmenu
    defaults:   { _controller: AppBundle:FrontOfficeVerticalMenu:partsMenu }

front_office_vertical_menu_specialties_country:
    path:       /all/specialties-country
    defaults:   { _controller: AppBundle:FrontOfficeVerticalMenu:specialtiesCountry }

front_office_vertical_menu_cooking_recipes:
    path:       /all/cooking-recipes/{page}
    defaults:   { _controller: AppBundle:FrontOfficeVerticalMenu:cookingRecipes, page: 1 }
    requirements:
        page:       \d*