manage_account_user:
    path:       /admin0081/user
    defaults:   { _controller: AppBundle:ManageAccount:user }

manage_account_user_activate:
    path:       /admin0081/utilisateur/activer/{id}
    defaults:   { _controller: AppBundle:ManageAccount:userActivate }

manage_account_user_desactivate:
    path:       /admin0081/user/desactiver/{id}
    defaults:   { _controller: AppBundle:ManageAccount:userDesactivate }

manage_account_user_modify_role:
    path:       /admin0081/utilisateur/modifier-role/{id}
    defaults:   { _controller: AppBundle:ManageAccount:userModifyRole }

manage_account_admin:
    path:       /admin0081/admin
    defaults:   { _controller: AppBundle:ManageAccount:admin }

manage_account_admin_activate:
    path:       /admin0081/admin/activer/{id}
    defaults:   { _controller: AppBundle:ManageAccount:adminActivate }

manage_account_admin_desactivate:
    path:       /admin0081/admin/desactiver/{id}
    defaults:   { _controller: AppBundle:ManageAccount:adminDesactivate }

manage_account_admin_modify_role:
    path:       /admin0081/admin/modifier-role/{id}
    defaults:   { _controller: AppBundle:ManageAccount:adminModifyRole }



