manage_part_of_menu_index:
    path:       /admin0081/part-menu
    defaults:   { _controller: AppBundle:ManagePartOfMenu:index }

manage_part_of_menu_add:
    path:       /admin0081/part-menu/ajouter
    defaults:   { _controller: AppBundle:ManagePartOfMenu:add }

manage_part_of_menu_edit:
    path:       /admin0081/part-menu/modifier/{id}-{slug}
    defaults:   { _controller: AppBundle:ManagePartOfMenu:edit }

manage_part_of_menu_delete:
    path:       /admin0081/part-menu/supprimer/{id}-{slug}
    defaults:   { _controller: AppBundle:ManagePartOfMenu:delete }