manage_cooking_recipe_index:
    path:       /admin0081/cooking_recipe
    defaults:   { _controller: AppBundle:ManageCookingRecipe:index }

manage_cooking_recipe_add:
    path:       /admin0081/cooking_recipe/ajouter
    defaults:   { _controller: AppBundle:ManageCookingRecipe:add }

manage_cooking_recipe_edit:
    path:       /admin0081/cooking_recipe/modifier/{id}
    defaults:   { _controller: AppBundle:ManageCookingRecipe:edit }

manage_cooking_recipe_delete:
    path:       /admin0081/cooking_recipe/supprimer/{id}
    defaults:   { _controller: AppBundle:ManageCookingRecipe:delete }