manage_ingredient_category_index:
    path:       /admin0081/ingredient-category
    defaults:   { _controller: AppBundle:ManageIngredientCategory:index }

manage_ingredient_category_add:
    path:       /admin0081/ingredient-category/ajouter
    defaults:   { _controller: AppBundle:ManageIngredientCategory:add }

manage_ingredient_category_edit:
    path:       /admin0081/ingredient-category/modifier/{id}
    defaults:   { _controller: AppBundle:ManageIngredientCategory:edit }

manage_ingredient_category_delete:
    path:       /admin0081/ingredient-category/delete/{id}
    defaults:   { _controller: AppBundle:ManageIngredientCategory:delete }