manage_ingredient_category_index:
    path:       /admin0081/ingredient-category
    defaults:   { _controller: AppBundle:ManageIngredientCategory:index }

manage_ingredient_category_add:
    path:       /admin0081/ingredient-category/ajouter
    defaults:   { _controller: AppBundle:ManageIngredientCategory:add }