manage_ingredient_index:
    path:       /admin0081/ingredient
    defaults:   { _controller: AppBundle:ManageIngredient:index }

manage_ingredient_add:
    path:       /admin0081/ingredient/ajouter
    defaults:   { _controller: AppBundle:ManageIngredient:add }

manage_ingredient_edit:
    path:       /admin0081/ingredient/modifier/{id}-{slug}
    defaults:   { _controller: AppBundle:ManageIngredient:edit }

manage_ingredient_delete:
    path:       /admin0081/ingredient/supprimer/{id}-{slug}
    defaults:   { _controller: AppBundle:ManageIngredient:delete }