manage_account_user:
    path:       /admin0081/user
    defaults:   { _controller: AppBundle:ManageAccount:user }

manage_account_admin:
    path:       /admin0081/Admin
    defaults:   { _controller: AppBundle:ManageAccount:admin }


